set -l black 1c1b19
set -l red ef2f27
set -l green 519f50
set -l yellow fbb829
set -l blue 2c78bf
set -l magenta e02c6d
set -l cyan 0aaeb3
set -l white d0bfa1
set -l bright_black 918175
set -l bright_red f75341
set -l bright_green 98bc37
set -l bright_yellow fed06e
set -l bright_blue 68a8e4
set -l bright_magenta ff5c8f
set -l bright_cyan 53fde9
set -l bright_white fce8c3

set -l orange ff5f00
set -l bright_orange ff8700
set -l hard_black 121212
set -l xgray1 262626
set -l xgray2 303030
set -l xgray3 3a3a3a
set -l xgray4 444444
set -l xgray5 4e4e4e
set -l xgray6 585858

# Syntax Highlighting Colors
set -g fish_color_normal $white
set -g fish_color_command $bright_white
set -g fish_color_quote $bright_green
set -g fish_color_redirection $white
set -g fish_color_end $orange
set -g fish_color_error $red
set -g fish_color_param $cyan
set -g fish_color_comment $bright_black
set -g fish_color_match --background=$xgray2
set -g fish_color_selection --background=$xgray2
set -g fish_color_search_match --background=$xgray2
set -g fish_color_operator $yellow
set -g fish_color_escape $bright_magenta
set -g fish_color_autosuggestion $bright_black

# Completion Pager Colors
set -g fish_pager_color_progress $bright_black
set -g fish_pager_color_prefix $cyan
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
